user_group_settings:
  valid_person_states:
    - awake
    - wakeup
    - winddown
    - asleep

users:
  nick:
    guest: false
    icons_home_away:
      auto: mdi:auto-fix
      home: mdi:home
      not_home: mdi:home-off
      unknown: mdi:home-search
    icons_state:
      awake: mdi:human-male
      winddown: mdi:alien
      asleep: mdi:bed
      absent: mdi:cancel
    tracking_entity: person.nick_davies

  partner:
    guest: false
    icons_state:
      awake: mdi:human-female
      winddown: mdi:alien-outline
      asleep: mdi:bed-outline
      absent: mdi:cancel

  guest_1:
    guest: true
    icon_exists: mdi:account-question
    icons_state:
      awake: mdi:account-clock
      winddown: mdi:arrow-down-bold-box
      asleep: mdi:bed-double
      absent: mdi:cancel

  guest_2:
    guest: true
    icon_exists: mdi:account-question-outline
    icons_state:
      awake: mdi:account-clock-outline
      winddown: mdi:arrow-down-bold-box-outline
      asleep: mdi:bed-double-outline
      absent: mdi:cancel

groups:
  primary:
    nick:
    partner:

  guests:
    guest_1:
    guest_2:

  everyone:
    primary:
    guests:

light_profiles:
  enable:
    enabled: true
  disable:
    enabled: false
  full:
    enabled: true
    brightness_pct: 100
  half:
    enabled: true
    brightness_pct: 50
  dim:
    enabled: true
    brightness_pct: 25
  night_light:
    enabled: true
    brightness_pct: 5

light_rule_templates:
   # For any area thats generally owned by a single group (because this is an exhaustive match).
   # it prefers the "most awake" state in the options. So this wouldn't be suitable for anything
   # that is sensitive
   prefer_awake:
     awake: full
     winddown: dim
     asleep: disable
     asleep_awake: full
     asleep_winddown: dim
     asleep_winddown_awake: full
     winddown_awake: full

   # For any area thats generally owned by a single group (because this is an exhaustive match).
   # it prefers the "most asleep" state in the options. So this wouldn't be suitable for anything
   # that is pretty private and wont effect others
   prefer_asleep:
     awake: full
     winddown: dim
     asleep: disable
     asleep_awake: disable
     asleep_winddown: disable
     asleep_winddown_awake: disable
     winddown_awake: dim

light_templates:
  private:
    no_motion_wait: 180
    default_profile: disable
    no_motion_profile: disable
    light_profile_rule_sets:
        - group: everyone
          rule_template: prefer_awake
  communal:
    no_motion_wait: 180
    default_profile: disable
    no_motion_profile: disable
    light_profile_rule_sets:
        - group: everyone
          rule_template: prefer_awake
  sensitive:
    no_motion_wait: 180
    default_profile: disable
    no_motion_profile: disable
    light_profile_rule_sets:
        - group: everyone
          rule_template: prefer_asleep


light_bindings:
