
settings:
  debug_dashboard:
  room:
    valid_room_states:
      - auto
      - manual
      # - scene
  user_group:
    valid_person_states:
      - awake
      - winddown
      - asleep

users:
  nick:
    guest: false
    icons_home_away:
      auto: mdi:auto-fix
      home: mdi:home
      not_home: mdi:home-off
      unknown: mdi:home-search
    icons_state:
      awake: mdi:human-male
      winddown: mdi:alien
      asleep: mdi:bed
      absent: mdi:cancel
    tracking_entity: person.nick_davies

  partner:
    guest: false
    icons_state:
      awake: mdi:human-female
      winddown: mdi:alien-outline
      asleep: mdi:bed-outline
      absent: mdi:cancel

  guest_1:
    guest: true
    icon_exists: mdi:account-question
    icons_state:
      awake: mdi:account-clock
      winddown: mdi:arrow-down-bold-box
      asleep: mdi:bed-double
      absent: mdi:cancel

  guest_2:
    guest: true
    icon_exists: mdi:account-question-outline
    icons_state:
      awake: mdi:account-clock-outline
      winddown: mdi:arrow-down-bold-box-outline
      asleep: mdi:bed-double-outline
      absent: mdi:cancel

groups:
  primary:
    - nick
    - partner

  guests:
    - guest_1
    - guest_2

  everyone:
    - nick
    - partner
    - guest_1
    - guest_2


light_profiles:
  enabled:
    enabled: true
    icon: mdi:lightbulb-on
  disabled:
    enabled: false
    icon: mdi:lightbulb-off
  full:
    enabled: true
    brightness_pct: 100
    icon: mdi:weather-sunny
  half:
    enabled: true
    brightness_pct: 50
    icon: mdi:lightbulb-on-50
  dim:
    enabled: true
    brightness_pct: 25
    icon: mdi:lamp
  nightlight:
    enabled: true
    brightness_pct: 5
    icon: mdi:weather-night
  noop: {}


templates:
  light_config_rules:
    # This is usually a sane default to have for every light group.
    # It provides being off when people are away, not touching the lights
    # when they are in cooldown or manual mode
    default_rules:
      inputs:
        - users
      template:
        - state_name: absent
          room_state: auto
          occupancy: "*"
          user_state:
            - user: "{users}"
              state_exact: absent
          light_profile: disabled
        # If the lights are auto and noone is there then turn off
        - state_name: empty
          room_state: auto
          occupancy: empty
          user_state: "*"
          light_profile: disabled

        # If the lights are auto and noone is there but there was someone recently
        # wait.
        - state_name: occupied_timeout
          room_state: auto
          occupancy: occupied_timeout
          user_state: "*"
          light_profile: noop

        # If the lights are in manual mode don't touch them!
        - state_name: manual
          room_state: manual
          occupancy: "*"
          user_state: "*"
          light_profile: noop

        - state_name: unknown_occ
          room_state: "*"
          occupancy: "*"
          user_state: "*"
          light_profile: noop

    # When the user is asleep then we want the nightlight for this room when it's occupied
    nightlight_on_demand:
      inputs:
        - users
      template:
        - state_name: nightlight
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{users}"
              state_any: asleep
          light_profile: nightlight

    prefer_awake:
      inputs:
        - users
      template:
        - state_name: someone_awake
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{users}"
              state_any: awake
          light_profile: full
        - state_name: someone_winddown
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{users}"
              state_any: winddown
          light_profile: dim
        - state_name: someone_asleep
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{users}"
              state_any: asleep
          light_profile: disabled

    prefer_asleep:
      inputs:
        - users
      template:
        - state_name: someone_asleep
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{users}"
              state_any: asleep
          light_profile: disabled
        - state_name: someone_winddown
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{users}"
              state_any: winddown
          light_profile: dim
        - state_name: someone_awake
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{users}"
              state_any: awake
          light_profile: full

    sensitive:
      inputs:
        - all_users
        - sensitive_users
        - safe_profile
      template:
        - state_name: everyone_asleep
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{all_users}"
              state_any: asleep
          light_profile: disabled
        - state_name: someone_asleep
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{sensitive_users}"
              state_any: asleep
          light_profile: "{safe_profile}"
        - state_name: someone_winddown
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{sensitive_users}"
              state_any: winddown
          light_profile: dim
        - state_name: everyone_awake
          room_state: auto
          occupancy: occupied
          user_state:
            - user: "{sensitive_users}"
              state_exact: awake
          light_profile: full


light_configs:
  main_bathroom_toilet:
    lights: light.main_bathroom_lights_toilet
    occupancy_sensors: binary_sensor.main_bathroom_sensor_toilet_occupancy
    occupancy_timeout: 180
    user: primary
    light_profile_rules:
      - template: default_rules
        values:
          users: primary
      - state_name: someone_asleep
        room_state: auto
        occupancy: occupied
        user_state:
          - user: primary
            state_any: asleep
        light_profile: disabled
      - template: nightlight_on_demand
        values:
          users: primary
      - template: prefer_asleep
        values:
          users: primary

  rooms_hall:
    lights: light.rooms_hall_lights_all
    occupancy_sensors:
      - binary_sensor.rooms_hall_sensor_main_bedroom_occupancy
      - binary_sensor.rooms_hall_sensor_office_entry_occupancy
    occupancy_timeout: 180
    user: everyone
    light_profile_rules:
      - template: default_rules
        values:
          users: everyone
      - template: sensitive
        values:
          all_users: everyone
          sensitive_users: everyone
          safe_profile: dim


